In [9]:
import requests # library to handle requests
import pandas as pd # library for data analsysis
import numpy as np # library to handle data in a vectorized manner
import random # library for random number generation

!conda install -c conda-forge geopy --yes 
from geopy.geocoders import Nominatim # module to convert an address into latitude and longitude values

# libraries for displaying images
from IPython.display import Image 
from IPython.core.display import HTML 
    
# tranforming json file into a pandas dataframe library
from pandas.io.json import json_normalize

!conda install -c conda-forge folium=0.5.0 --yes
import folium # plotting library

print('Folium installed')
print('Libraries imported.')

Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/jupyterlab/conda/envs/python

  added / updated specs:
    - geopy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    geographiclib-1.50         |             py_0          34 KB  conda-forge
    geopy-1.21.0               |             py_0          58 KB  conda-forge
    ------------------------------------------------------------
                                           Total:          92 KB

The following NEW packages will be INSTALLED:

  geographiclib      conda-forge/noarch::geographiclib-1.50-py_0
  geopy              conda-forge/noarch::geopy-1.21.0-py_0



Downloading and Extracting Packages
geopy-1.21.0         | 58 KB     | ##################################### | 100%
geographiclib-1.50   | 34 KB     | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/jupyterlab/conda/envs/python

  added / updated specs:
    - folium=0.5.0


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    altair-4.1.0               |             py_1         614 KB  conda-forge
    branca-0.4.0               |             py_0          26 KB  conda-forge
    brotlipy-0.7.0             |py36h8c4c3a4_1000         346 KB  conda-forge
    chardet-3.0.4              |py36h9f0ad1d_1006         188 KB  conda-forge
    cryptography-2.8           |   py36h45558ae_2         628 KB  conda-forge
    folium-0.5.0               |             py_0          45 KB  conda-forge
    pandas-1.0.3               |   py36h830a2c2_1        11.1 MB  conda-forge
    pysocks-1.7.1              |   py36h9f0ad1d_1          27 KB  conda-forge
    toolz-0.10.0               |             py_0          46 KB  conda-forge
    urllib3-1.25.9             |             py_0          92 KB  conda-forge
    vincent-0.4.4              |             py_1          28 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        13.1 MB

The following NEW packages will be INSTALLED:

  altair             conda-forge/noarch::altair-4.1.0-py_1
  attrs              conda-forge/noarch::attrs-19.3.0-py_0
  branca             conda-forge/noarch::branca-0.4.0-py_0
  brotlipy           conda-forge/linux-64::brotlipy-0.7.0-py36h8c4c3a4_1000
  chardet            conda-forge/linux-64::chardet-3.0.4-py36h9f0ad1d_1006
  cryptography       conda-forge/linux-64::cryptography-2.8-py36h45558ae_2
  entrypoints        conda-forge/linux-64::entrypoints-0.3-py36h9f0ad1d_1001
  folium             conda-forge/noarch::folium-0.5.0-py_0
  idna               conda-forge/noarch::idna-2.9-py_1
  importlib-metadata conda-forge/linux-64::importlib-metadata-1.6.0-py36h9f0ad1d_0
  importlib_metadata conda-forge/noarch::importlib_metadata-1.6.0-0
  jinja2             conda-forge/noarch::jinja2-2.11.2-pyh9f0ad1d_0
  jsonschema         conda-forge/linux-64::jsonschema-3.2.0-py36h9f0ad1d_1
  markupsafe         conda-forge/linux-64::markupsafe-1.1.1-py36h8c4c3a4_1
  pandas             conda-forge/linux-64::pandas-1.0.3-py36h830a2c2_1
  pyopenssl          conda-forge/noarch::pyopenssl-19.1.0-py_1
  pyrsistent         conda-forge/linux-64::pyrsistent-0.16.0-py36h8c4c3a4_0
  pysocks            conda-forge/linux-64::pysocks-1.7.1-py36h9f0ad1d_1
  pytz               conda-forge/noarch::pytz-2019.3-py_0
  requests           conda-forge/noarch::requests-2.23.0-pyh8c360ce_2
  toolz              conda-forge/noarch::toolz-0.10.0-py_0
  urllib3            conda-forge/noarch::urllib3-1.25.9-py_0
  vincent            conda-forge/noarch::vincent-0.4.4-py_1
  zipp               conda-forge/noarch::zipp-3.1.0-py_0



Downloading and Extracting Packages
pysocks-1.7.1        | 27 KB     | ##################################### | 100%
cryptography-2.8     | 628 KB    | ##################################### | 100%
toolz-0.10.0         | 46 KB     | ##################################### | 100%
chardet-3.0.4        | 188 KB    | ##################################### | 100%
folium-0.5.0         | 45 KB     | ##################################### | 100%
urllib3-1.25.9       | 92 KB     | ##################################### | 100%
brotlipy-0.7.0       | 346 KB    | ##################################### | 100%
pandas-1.0.3         | 11.1 MB   | ##################################### | 100%
altair-4.1.0         | 614 KB    | ##################################### | 100%
branca-0.4.0         | 26 KB     | ##################################### | 100%
vincent-0.4.4        | 28 KB     | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Folium installed
Libraries imported.

import foursquare credential

In [4]:
CLIENT_ID = 'STHLWLIIXLEQNBQMRLEESTN0A55X1M0IF03LSAJVF1NBSXBV' # your Foursquare ID
CLIENT_SECRET = 'OGGDLS5GKWNIRD5IIMSF2BYTYHEYXNTCZ1L4WD2ON2514JB1' # your Foursquare Secret
VERSION = '20180604'
LIMIT = 30
print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: STHLWLIIXLEQNBQMRLEESTN0A55X1M0IF03LSAJVF1NBSXBV
CLIENT_SECRET:OGGDLS5GKWNIRD5IIMSF2BYTYHEYXNTCZ1L4WD2ON2514JB1

define areas of interest as the starting points: Shanghai, Seattle, New York, San Francisco

define categories:see https://developer.foursquare.com/docs/build-with-foursquare/categories/

In [5]:
categoryId = '4d4b7105d754a06374d81259'     #category id for food
near ='New York,NY'
print(categoryId + near + ' .... OK!')

4d4b7105d754a06374d81259New York,NY .... OK!

In [6]:
url = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&near={}&categoryId={}&v={}&limit={}'.format(CLIENT_ID, CLIENT_SECRET, near, categoryId, VERSION, LIMIT)
url

'https://api.foursquare.com/v2/venues/search?client_id=STHLWLIIXLEQNBQMRLEESTN0A55X1M0IF03LSAJVF1NBSXBV&client_secret=OGGDLS5GKWNIRD5IIMSF2BYTYHEYXNTCZ1L4WD2ON2514JB1&near=New York,NY&categoryId=4d4b7105d754a06374d81259&v=20180604&limit=30'

get json results and reformat

In [10]:
results = requests.get(url).json()
results

{'meta': {'code': 200, 'requestId': '5e9bc89a83525f002907bf6b'},
 'response': {'venues': [{'id': '4c5ef77bfff99c74eda954d3',
    'name': 'Eataly Flatiron',
    'location': {'address': '200 5th Ave',
     'crossStreet': 'at W 23rd St',
     'lat': 40.74198696405861,
     'lng': -73.98991319280194,
     'labeledLatLngs': [{'label': 'display',
       'lat': 40.74198696405861,
       'lng': -73.98991319280194}],
     'postalCode': '10010',
     'cc': 'US',
     'city': 'New York',
     'state': 'NY',
     'country': 'United States',
     'formattedAddress': ['200 5th Ave (at W 23rd St)',
      'New York, NY 10010',
      'United States']},
    'categories': [{'id': '4bf58dd8d48988d1f5941735',
      'name': 'Gourmet Shop',
      'pluralName': 'Gourmet Shops',
      'shortName': 'Gourmet',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/shops/food_gourmet_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1587267800',
    'hasPerk': False},
   {'id': '5b76dcc19fca56002de565df',
    'name': "Dunkin'",
    'location': {'address': '1410 N Broad St',
     'lat': 40.69785456739121,
     'lng': -74.21754387486874,
     'labeledLatLngs': [{'label': 'display',
       'lat': 40.69785456739121,
       'lng': -74.21754387486874}],
     'postalCode': '07205',
     'cc': 'US',
     'city': 'Hillside',
     'state': 'NJ',
     'country': 'United States',
     'formattedAddress': ['1410 N Broad St',
      'Hillside, NJ 07205',
      'United States']},
    'categories': [{'id': '4bf58dd8d48988d148941735',
      'name': 'Donut Shop',
      'pluralName': 'Donut Shops',
      'shortName': 'Donuts',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/donuts_',
       'suffix': '.png'},
      'primary': True}],
    'delivery': {'id': '1394893',
     'url': 'https://www.grubhub.com/restaurant/dunkin-1410-n-broad-st-hillside/1394893?affiliate=1131&utm_source=foursquare-affiliate-network&utm_medium=affiliate&utm_campaign=1131&utm_content=1394893',
     'provider': {'name': 'grubhub',
      'icon': {'prefix': 'https://fastly.4sqi.net/img/general/cap/',
       'sizes': [40, 50],
       'name': '/delivery_provider_grubhub_20180129.png'}}},
    'referralId': 'v-1587267800',
    'hasPerk': False},
   {'id': '562e8930498e260cde609d13',
    'name': "Armando's Kitchen",
    'location': {'address': '1345 Rockaway Pkwy',
     'lat': 40.64685639184821,
     'lng': -73.90418877151708,
     'labeledLatLngs': [{'label': 'display',
       'lat': 40.64685639184821,
       'lng': -73.90418877151708},
      {'label': 'entrance', 'lat': 40.646937, 'lng': -73.904151}],
     'postalCode': '11236',
     'cc': 'US',
     'city': 'Brooklyn',
     'state': 'NY',
     'country': 'United States',
     'formattedAddress': ['1345 Rockaway Pkwy',
      'Brooklyn, NY 11236',
      'United States']},
    'categories': [{'id': '4bf58dd8d48988d110941735',
      'name': 'Italian Restaurant',
      'pluralName': 'Italian Restaurants',
      'shortName': 'Italian',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/italian_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1587267800',
    'hasPerk': False},
   {'id': '5cf465f1829b0c002c5552f7',
    'name': 'Coolsville',
    'location': {'lat': 40.860077,
     'lng': -73.930597,
     'labeledLatLngs': [{'label': 'display',
       'lat': 40.860077,
       'lng': -73.930597}],
     'postalCode': '10040',
     'cc': 'US',
     'city': 'New York',
     'state': 'NY',
     'country': 'United States',
     'formattedAddress': ['New York, NY 10040', 'United States']},
    'categories': [{'id': '4bf58dd8d48988d157941735',
      'name': 'New American Restaurant',
      'pluralName': 'New American Restaurants',
      'shortName': 'New American',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/newamerican_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1587267800',
    'hasPerk': False},
   {'id': '40e74880f964a520150a1fe3',
    'name': 'Shake Shack',
    'location': {'address': 'Southeast corner of Madison Square Park',
     'crossStreet': 'Madison Ave & E 23rd St',
     'lat': 40.74148371088094,
     'lng': -73.9882180094719,
     'labeledLatLngs': [{'label': 'display',
       'lat': 40.74148371088094,
       'lng': -73.9882180094719}],
     'postalCode': '10010',
     'cc': 'US',
     'neighborhood': 'Flatiron',
     'city': 'New York',
     'state': 'NY',
     'country': 'United States',
     'formattedAddress': ['Southeast corner of Madison Square Park (Madison Ave & E 23rd St)',
      'New York, NY 10010',
      'United States']},
    'categories': [{'id': '4bf58dd8d48988d16c941735',
      'name': 'Burger Joint',
      'pluralName': 'Burger Joints',
      'shortName': 'Burgers',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/burger_',
       'suffix': '.png'},
      'primary': True}],
    'delivery': {'id': '698246',
     'url': 'https://www.seamless.com/menu/shake-shack-23rd-st--madison-ave-new-york/698246?affiliate=1131&utm_source=foursquare-affiliate-network&utm_medium=affiliate&utm_campaign=1131&utm_content=698246',
     'provider': {'name': 'seamless',
      'icon': {'prefix': 'https://fastly.4sqi.net/img/general/cap/',
       'sizes': [40, 50],
       'name': '/delivery_provider_seamless_20180129.png'}}},
    'referralId': 'v-1587267800',
    'hasPerk': False},
   {'id': '5b8e66ac234724002c927c4b',
    'name': 'Brooklyn Bagel & Coffee Company',
    'location': {'address': '63 E 8th St',
     'crossStreet': 'Mercer Street',
     'lat': 40.730912575619136,
     'lng': -73.9932591437105,
     'labeledLatLngs': [{'label': 'display',
       'lat': 40.730912575619136,
       'lng': -73.9932591437105}],
     'postalCode': '10003',
     'cc': 'US',
     'city': 'New York',
     'state': 'NY',
     'country': 'United States',
     'formattedAddress': ['63 E 8th St (Mercer Street)',
      'New York, NY 10003',
      'United States']},
    'categories': [{'id': '4bf58dd8d48988d179941735',
      'name': 'Bagel Shop',
      'pluralName': 'Bagel Shops',
      'shortName': 'Bagels',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/bagels_',
       'suffix': '.png'},
      'primary': True}],
    'delivery': {'id': '2036373',
     'url': 'https://www.seamless.com/menu/brooklyn-bagel--coffee-company---greenwich-village-63-e-8th-st-new-york/2036373?affiliate=1131&utm_source=foursquare-affiliate-network&utm_medium=affiliate&utm_campaign=1131&utm_content=2036373',
     'provider': {'name': 'seamless',
      'icon': {'prefix': 'https://fastly.4sqi.net/img/general/cap/',
       'sizes': [40, 50],
       'name': '/delivery_provider_seamless_20180129.png'}}},
    'referralId': 'v-1587267800',
    'hasPerk': False},
   {'id': '57435943498e03ad20563e5f',
    'name': 'Pommes Frites',
    'location': {'address': '128 Macdougal St',
     'lat': 40.73015312099686,
     'lng': -74.00031745632894,
     'labeledLatLngs': [{'label': 'display',
       'lat': 40.73015312099686,
       'lng': -74.00031745632894}],
     'postalCode': '10012',
     'cc': 'US',
     'city': 'New York',
     'state': 'NY',
     'country': 'United States',
     'formattedAddress': ['128 Macdougal St',
      'New York, NY 10012',
      'United States']},
    'categories': [{'id': '56aa371be4b08b9a8d5734c7',
      'name': 'Poutine Place',
      'pluralName': 'Poutine Places',
      'shortName': 'Poutine Place',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/fastfood_',
       'suffix': '.png'},
      'primary': True}],
    'delivery': {'id': '907346',
     'url': 'https://www.seamless.com/menu/pommes-frites-128-macdougal-st-new-york/907346?affiliate=1131&utm_source=foursquare-affiliate-network&utm_medium=affiliate&utm_campaign=1131&utm_content=907346',
     'provider': {'name': 'seamless',
      'icon': {'prefix': 'https://fastly.4sqi.net/img/general/cap/',
       'sizes': [40, 50],
       'name': '/delivery_provider_seamless_20180129.png'}}},
    'venuePage': {'id': '192404561'},
    'referralId': 'v-1587267800',
    'hasPerk': False},
   {'id': '4c698ebec946e21ecd7dea8e',
    'name': 'Mondial Bakery',
    'location': {'lat': 40.60903786,
     'lng': -73.99066898018644,
     'labeledLatLngs': [{'label': 'display',
       'lat': 40.60903786,
       'lng': -73.99066898018644}],
     'postalCode': '11214',
     'cc': 'US',
     'city': 'Brooklyn',
     'state': 'NY',
     'country': 'United States',
     'formattedAddress': ['Brooklyn, NY 11214', 'United States']},
    'categories': [{'id': '4bf58dd8d48988d16a941735',
      'name': 'Bakery',
      'pluralName': 'Bakeries',
      'shortName': 'Bakery',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/bakery_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1587267800',
    'hasPerk': False},
   {'id': '5cc3adaa838e59002cb4629d',
    'name': 'Rezdôra',
    'location': {'address': '27 E 20th St',
     'crossStreet': 'Broadway & Park Avenue South',
     'lat': 40.738941,
     'lng': -73.988862,
     'labeledLatLngs': [{'label': 'display',
       'lat': 40.738941,
       'lng': -73.988862}],
     'postalCode': '10003',
     'cc': 'US',
     'city': 'New York',
     'state': 'NY',
     'country': 'United States',
     'formattedAddress': ['27 E 20th St (Broadway & Park Avenue South)',
      'New York, NY 10003',
      'United States']},
    'categories': [{'id': '4bf58dd8d48988d110941735',
      'name': 'Italian Restaurant',
      'pluralName': 'Italian Restaurants',
      'shortName': 'Italian',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/italian_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1587267800',
    'hasPerk': False},
   {'id': '5d2ccef540f3b0002ffe517d',
    'name': 'Levain Bakery',
    'location': {'address': '1484 3rd Ave',
     'lat': 40.777354,
     'lng': -73.955284,
     'labeledLatLngs': [{'label': 'display',
       'lat': 40.777354,
       'lng': -73.955284},
      {'label': 'entrance', 'lat': 40.777377, 'lng': -73.955245}],
     'postalCode': '10028',
     'cc': 'US',
     'city': 'New York',
     'state': 'NY',
     'country': 'United States',
     'formattedAddress': ['1484 3rd Ave',
      'New York, NY 10028',
      'United States']},
    'categories': [{'id': '4bf58dd8d48988d16a941735',
      'name': 'Bakery',
      'pluralName': 'Bakeries',
      'shortName': 'Bakery',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/bakery_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1587267800',
    'hasPerk': False},
   {'id': '5a860dbd911fc47c1a800325',
    'name': 'H Mart',
    'location': {'address': '2828 Broadway',
     'lat': 40.80401565017113,
     'lng': -73.96667439065985,
     'labeledLatLngs': [{'label': 'display',
       'lat': 40.80401565017113,
       'lng': -73.96667439065985}],
     'postalCode': '10025',
     'cc': 'US',
     'city': 'New York',
     'state': 'NY',
     'country': 'United States',
     'formattedAddress': ['2828 Broadway',
      'New York, NY 10025',
      'United States']},
    'categories': [{'id': '4bf58dd8d48988d118951735',
      'name': 'Grocery Store',
      'pluralName': 'Grocery Stores',
      'shortName': 'Grocery Store',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/shops/food_grocery_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1587267800',
    'hasPerk': False},
   {'id': '5cd0190f3af988002c46b0c0',
    'name': 'Essex Market',
    'location': {'address': '88 Essex St',
     'crossStreet': 'at Delancey St',
     'lat': 40.71802545259831,
     'lng': -73.98824699849924,
     'labeledLatLngs': [{'label': 'display',
       'lat': 40.71802545259831,
       'lng': -73.98824699849924}],
     'postalCode': '10002',
     'cc': 'US',
     'neighborhood': 'Lower East Side',
     'city': 'New York',
     'state': 'NY',
     'country': 'United States',
     'formattedAddress': ['88 Essex St (at Delancey St)',
      'New York, NY 10002',
      'United States']},
    'categories': [{'id': '4bf58dd8d48988d120951735',
      'name': 'Food Court',
      'pluralName': 'Food Courts',
      'shortName': 'Food Court',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/shops/food_foodcourt_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1587267800',
    'hasPerk': False},
   {'id': '4d1bcc79763fb1f7fe7d8566',
    'name': 'Han Nam Mart',
    'location': {'address': '1475 Bergen Blvd',
     'lat': 40.8517748921657,
     'lng': -73.98641694909082,
     'labeledLatLngs': [{'label': 'display',
       'lat': 40.8517748921657,
       'lng': -73.98641694909082}],
     'postalCode': '07024',
     'cc': 'US',
     'city': 'Fort Lee',
     'state': 'NJ',
     'country': 'United States',
     'formattedAddress': ['1475 Bergen Blvd',
      'Fort Lee, NJ 07024',
      'United States']},
    'categories': [{'id': '4bf58dd8d48988d118951735',
      'name': 'Grocery Store',
      'pluralName': 'Grocery Stores',
      'shortName': 'Grocery Store',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/shops/food_grocery_',
       'suffix': '.png'},
      'primary': True}],
    'delivery': {'id': '1532168',
     'url': 'https://www.grubhub.com/restaurant/han-nam-1475-bergen-blvd-fort-lee/1532168?affiliate=1131&utm_source=foursquare-affiliate-network&utm_medium=affiliate&utm_campaign=1131&utm_content=1532168',
     'provider': {'name': 'grubhub',
      'icon': {'prefix': 'https://fastly.4sqi.net/img/general/cap/',
       'sizes': [40, 50],
       'name': '/delivery_provider_grubhub_20180129.png'}}},
    'referralId': 'v-1587267800',
    'hasPerk': False},
   {'id': '586d976988641b556fe3882b',
    'name': 'Costco Food Court',
    'location': {'address': '32-50 Vernon Blvd',
     'lat': 40.76759946639263,
     'lng': -73.9379889483821,
     'labeledLatLngs': [{'label': 'display',
       'lat': 40.76759946639263,
       'lng': -73.9379889483821}],
     'postalCode': '11106',
     'cc': 'US',
     'city': 'Long Island City',
     'state': 'NY',
     'country': 'United States',
     'formattedAddress': ['32-50 Vernon Blvd',
      'Long Island City, NY 11106',
      'United States']},
    'categories': [{'id': '4bf58dd8d48988d120951735',
      'name': 'Food Court',
      'pluralName': 'Food Courts',
      'shortName': 'Food Court',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/shops/food_foodcourt_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1587267800',
    'hasPerk': False},
   {'id': '49f85cbbf964a520f26c1fe3',
    'name': 'Mitsuwa Marketplace',
    'location': {'address': '595 River Rd',
     'crossStreet': 'at Archer St',
     'lat': 40.81625111476336,
     'lng': -73.97998764962125,
     'labeledLatLngs': [{'label': 'display',
       'lat': 40.81625111476336,
       'lng': -73.97998764962125},
      {'label': 'entrance', 'lat': 40.816945, 'lng': -73.980323}],
     'postalCode': '07020',
     'cc': 'US',
     'city': 'Edgewater',
     'state': 'NJ',
     'country': 'United States',
     'formattedAddress': ['595 River Rd (at Archer St)',
      'Edgewater, NJ 07020',
      'United States']},
    'categories': [{'id': '52f2ab2ebcbc57f1066b8b46',
      'name': 'Supermarket',
      'pluralName': 'Supermarkets',
      'shortName': 'Supermarket',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/shops/food_grocery_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1587267800',
    'hasPerk': False},
   {'id': '5295f62511d24c029a9ec2d9',
    'name': 'Hungry Ghost',
    'location': {'address': '781 Fulton St',
     'crossStreet': 'at S. Oxford St',
     'lat': 40.686019848047394,
     'lng': -73.97355641043038,
     'labeledLatLngs': [{'label': 'display',
       'lat': 40.686019848047394,
       'lng': -73.97355641043038}],
     'postalCode': '11217',
     'cc': 'US',
     'city': 'Brooklyn',
     'state': 'NY',
     'country': 'United States',
     'formattedAddress': ['781 Fulton St (at S. Oxford St)',
      'Brooklyn, NY 11217',
      'United States']},
    'categories': [{'id': '4bf58dd8d48988d1e0931735',
      'name': 'Coffee Shop',
      'pluralName': 'Coffee Shops',
      'shortName': 'Coffee Shop',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/coffeeshop_',
       'suffix': '.png'},
      'primary': True}],
    'venuePage': {'id': '94534477'},
    'referralId': 'v-1587267800',
    'hasPerk': False},
   {'id': '594277b586f4cc0f251fc389',
    'name': 'DeKalb Market Hall',
    'location': {'address': '445 Albee Sq',
     'lat': 40.69124975637413,
     'lng': -73.98257926844987,
     'labeledLatLngs': [{'label': 'display',
       'lat': 40.69124975637413,
       'lng': -73.98257926844987}],
     'postalCode': '11201',
     'cc': 'US',
     'city': 'Brooklyn',
     'state': 'NY',
     'country': 'United States',
     'formattedAddress': ['445 Albee Sq',
      'Brooklyn, NY 11201',
      'United States']},
    'categories': [{'id': '4bf58dd8d48988d120951735',
      'name': 'Food Court',
      'pluralName': 'Food Courts',
      'shortName': 'Food Court',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/shops/food_foodcourt_',
       'suffix': '.png'},
      'primary': True}],
    'delivery': {'id': '682503',
     'url': 'https://www.seamless.com/menu/two-tablespoons-dekalb-market-hall-445-albee-sq-brooklyn/682503?affiliate=1131&utm_source=foursquare-affiliate-network&utm_medium=affiliate&utm_campaign=1131&utm_content=682503',
     'provider': {'name': 'seamless',
      'icon': {'prefix': 'https://fastly.4sqi.net/img/general/cap/',
       'sizes': [40, 50],
       'name': '/delivery_provider_seamless_20180129.png'}}},
    'referralId': 'v-1587267800',
    'hasPerk': False},
   {'id': '4a4e83e6f964a52095ae1fe3',
    'name': 'C-Town Supermarkets',
    'location': {'address': '330 Graham Avenue',
     'lat': 40.714125963915784,
     'lng': -73.9440015676779,
     'labeledLatLngs': [{'label': 'display',
       'lat': 40.714125963915784,
       'lng': -73.9440015676779}],
     'postalCode': '11211',
     'cc': 'US',
     'city': 'Brooklyn',
     'state': 'NY',
     'country': 'United States',
     'formattedAddress': ['330 Graham Avenue',
      'Brooklyn, NY 11211',
      'United States']},
    'categories': [{'id': '4bf58dd8d48988d118951735',
      'name': 'Grocery Store',
      'pluralName': 'Grocery Stores',
      'shortName': 'Grocery Store',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/shops/food_grocery_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1587267800',
    'hasPerk': False},
   {'id': '59d2f415112c6c2e27dc7740',
    'name': 'Hutch and Waldo',
    'location': {'address': '247 E 81st St',
     'lat': 40.77476755883795,
     'lng': -73.95438884357908,
     'labeledLatLngs': [{'label': 'display',
       'lat': 40.77476755883795,
       'lng': -73.95438884357908}],
     'postalCode': '10028',
     'cc': 'US',
     'city': 'New York',
     'state': 'NY',
     'country': 'United States',
     'formattedAddress': ['247 E 81st St',
      'New York, NY 10028',
      'United States']},
    'categories': [{'id': '4bf58dd8d48988d1e0931735',
      'name': 'Coffee Shop',
      'pluralName': 'Coffee Shops',
      'shortName': 'Coffee Shop',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/coffeeshop_',
       'suffix': '.png'},
      'primary': True}],
    'delivery': {'id': '1003043',
     'url': 'https://www.seamless.com/menu/hutch--waldo-247-e-81-st-new-york/1003043?affiliate=1131&utm_source=foursquare-affiliate-network&utm_medium=affiliate&utm_campaign=1131&utm_content=1003043',
     'provider': {'name': 'seamless',
      'icon': {'prefix': 'https://fastly.4sqi.net/img/general/cap/',
       'sizes': [40, 50],
       'name': '/delivery_provider_seamless_20180129.png'}}},

transform into tabular format, keeping only the relevant part (e.g. venue name, geometry, )

In [13]:

venues = results['response']['venues']

# tranform venues into a dataframe
dataframe_NewYork = json_normalize(venues)
dataframe_NewYork

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/ipykernel_launcher.py:4: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  after removing the cwd from sys.path.

,id,name,categories,referralId,hasPerk,location.address,location.crossStreet,location.lat,location.lng,location.labeledLatLngs,...,location.country,location.formattedAddress,delivery.id,delivery.url,delivery.provider.name,delivery.provider.icon.prefix,delivery.provider.icon.sizes,delivery.provider.icon.name,location.neighborhood,venuePage.id
0,4c5ef77bfff99c74eda954d3,Eataly Flatiron,"[{'id': '4bf58dd8d48988d1f5941735', 'name': 'G...",v-1587267800,False,200 5th Ave,at W 23rd St,40.741987,-73.989913,"[{'label': 'display', 'lat': 40.74198696405861...",...,United States,"[200 5th Ave (at W 23rd St), New York, NY 1001...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5b76dcc19fca56002de565df,Dunkin',"[{'id': '4bf58dd8d48988d148941735', 'name': 'D...",v-1587267800,False,1410 N Broad St,NaN,40.697855,-74.217544,"[{'label': 'display', 'lat': 40.69785456739121...",...,United States,"[1410 N Broad St, Hillside, NJ 07205, United S...",1394893,https://www.grubhub.com/restaurant/dunkin-1410...,grubhub,https://fastly.4sqi.net/img/general/cap/,"[40, 50]",/delivery_provider_grubhub_20180129.png,NaN,NaN
2,562e8930498e260cde609d13,Armando's Kitchen,"[{'id': '4bf58dd8d48988d110941735', 'name': 'I...",v-1587267800,False,1345 Rockaway Pkwy,NaN,40.646856,-73.904189,"[{'label': 'display', 'lat': 40.64685639184821...",...,United States,"[1345 Rockaway Pkwy, Brooklyn, NY 11236, Unite...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5cf465f1829b0c002c5552f7,Coolsville,"[{'id': '4bf58dd8d48988d157941735', 'name': 'N...",v-1587267800,False,NaN,NaN,40.860077,-73.930597,"[{'label': 'display', 'lat': 40.860077, 'lng':...",...,United States,"[New York, NY 10040, United States]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,40e74880f964a520150a1fe3,Shake Shack,"[{'id': '4bf58dd8d48988d16c941735', 'name': 'B...",v-1587267800,False,Southeast corner of Madison Square Park,Madison Ave & E 23rd St,40.741484,-73.988218,"[{'label': 'display', 'lat': 40.74148371088094...",...,United States,[Southeast corner of Madison Square Park (Madi...,698246,https://www.seamless.com/menu/shake-shack-23rd...,seamless,https://fastly.4sqi.net/img/general/cap/,"[40, 50]",/delivery_provider_seamless_20180129.png,Flatiron,NaN
5,5b8e66ac234724002c927c4b,Brooklyn Bagel & Coffee Company,"[{'id': '4bf58dd8d48988d179941735', 'name': 'B...",v-1587267800,False,63 E 8th St,Mercer Street,40.730913,-73.993259,"[{'label': 'display', 'lat': 40.73091257561913...",...,United States,"[63 E 8th St (Mercer Street), New York, NY 100...",2036373,https://www.seamless.com/menu/brooklyn-bagel--...,seamless,https://fastly.4sqi.net/img/general/cap/,"[40, 50]",/delivery_provider_seamless_20180129.png,NaN,NaN
6,57435943498e03ad20563e5f,Pommes Frites,"[{'id': '56aa371be4b08b9a8d5734c7', 'name': 'P...",v-1587267800,False,128 Macdougal St,NaN,40.730153,-74.000317,"[{'label': 'display', 'lat': 40.73015312099686...",...,United States,"[128 Macdougal St, New York, NY 10012, United ...",907346,https://www.seamless.com/menu/pommes-frites-12...,seamless,https://fastly.4sqi.net/img/general/cap/,"[40, 50]",/delivery_provider_seamless_20180129.png,NaN,192404561
7,4c698ebec946e21ecd7dea8e,Mondial Bakery,"[{'id': '4bf58dd8d48988d16a941735', 'name': 'B...",v-1587267800,False,NaN,NaN,40.609038,-73.990669,"[{'label': 'display', 'lat': 40.60903786, 'lng...",...,United States,"[Brooklyn, NY 11214, United States]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,5cc3adaa838e59002cb4629d,Rezdôra,"[{'id': '4bf58dd8d48988d110941735', 'name': 'I...",v-1587267800,False,27 E 20th St,Broadway & Park Avenue South,40.738941,-73.988862,"[{'label': 'display', 'lat': 40.738941, 'lng':...",...,United States,"[27 E 20th St (Broadway & Park Avenue South), ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,5d2ccef540f3b0002ffe517d,Levain Bakery,"[{'id': '4bf58dd8d48988d16a941735', 'name': 'B...",v-1587267800,False,1484 3rd Ave,NaN,40.777354,-73.955284,"[{'label': 'display', 'lat': 40.777354, 'lng':...",...,United States,"[1484 3rd Ave, New York, NY 10028, United States]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,5a860dbd911fc47c1a800325,H Mart,"[{'id': '4bf58dd8d48988d118951735', 'name': 'G...",v-1587267800,False,2828 Broadway,NaN,40.804016,-73.966674,"[{'label': 'display', 'lat': 40.80401565017113...",...,United States,"[2828 Broadway, New York, NY 10025, United Sta...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,5cd0190f3af988002c46b0c0,Essex Market,"[{'id': '4bf58dd8d48988d120951735', 'name': 'F...",v-1587267800,False,88 Essex St,at Delancey St,40.718025,-73.988247,"[{'label': 'display', 'lat': 40.71802545259831...",...,United States,"[88 Essex St (at Delancey St), New York, NY 10...",NaN,NaN,NaN,NaN,NaN,NaN,Lower East Side,NaN
12,4d1bcc79763fb1f7fe7d8566,Han Nam Mart,"[{'id': '4bf58dd8d48988d118951735', 'name': 'G...",v-1587267800,False,1475 Bergen Blvd,NaN,40.851775,-73.986417,"[{'label': 'display', 'lat': 40.8517748921657,...",...,United States,"[1475 Bergen Blvd, Fort Lee, NJ 07024, United ...",1532168,https://www.grubhub.com/restaurant/han-nam-147...,grubhub,https://fastly.4sqi.net/img/general/cap/,"[40, 50]",/delivery_provider_grubhub_20180129.png,NaN,NaN
13,586d976988641b556fe3882b,Costco Food Court,"[{'id': '4bf58dd8d48988d120951735', 'name': 'F...",v-1587267800,False,32-50 Vernon Blvd,NaN,40.767599,-73.937989,"[{'label': 'display', 'lat': 40.76759946639263...",...,United States,"[32-50 Vernon Blvd, Long Island City, NY 11106...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,49f85cbbf964a520f26c1fe3,Mitsuwa Marketplace,"[{'id': '52f2ab2ebcbc57f1066b8b46', 'name': 'S...",v-1587267800,False,595 River Rd,at Archer St,40.816251,-73.979988,"[{'label': 'display', 'lat': 40.81625111476336...",...,United States,"[595 River Rd (at Archer St), Edgewater, NJ 07...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,5295f62511d24c029a9ec2d9,Hungry Ghost,"[{'id': '4bf58dd8d48988d1e0931735', 'name': 'C...",v-1587267800,False,781 Fulton St,at S. Oxford St,40.686020,-73.973556,"[{'label': 'display', 'lat': 40.68601984804739...",...,United States,"[781 Fulton St (at S. Oxford St), Brooklyn, NY...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,94534477
16,594277b586f4cc0f251fc389,DeKalb Market Hall,"[{'id': '4bf58dd8d48988d120951735', 'name': 'F...",v-1587267800,False,445 Albee Sq,NaN,40.691250,-73.982579,"[{'label': 'display', 'lat': 40.69124975637413...",...,United States,"[445 Albee Sq, Brooklyn, NY 11201, United States]",682503,https://www.seamless.com/menu/two-tablespoons-...,seamless,https://fastly.4sqi.net/img/general/cap/,"[40, 50]",/delivery_provider_seamless_20180129.png,NaN,NaN
17,4a4e83e6f964a52095ae1fe3,C-Town Supermarkets,"[{'id': '4bf58dd8d48988d118951735', 'name': 'G...",v-1587267800,False,330 Graham Avenue,NaN,40.714126,-73.944002,"[{'label': 'display', 'lat': 40.71412596391578...",...,United States,"[330 Graham Avenue, Brooklyn, NY 11211, United...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,59d2f415112c6c2e27dc7740,Hutch and Waldo,"[{'id': '4bf58dd8d48988d1e0931735', 'name': 'C...",v-1587267800,False,247 E 81st St,NaN,40.774768,-73.954389,"[{'label': 'display', 'lat': 40.77476755883795...",...,United States,"[247 E 81st St, New York, NY 10028, United Sta...",1003043,https://www.seamless.com/menu/hutch--waldo-247...,seamless,https://fastly.4sqi.net/img/general/cap/,"[40, 50]",/delivery_provider_seamless_20180129.png,NaN,NaN
19,579c12cd498e6e815b3acf50,Eataly Downtown,"[{'id': '4bf58dd8d48988d1f5941735', 'name': 'G...",v-1587267800,False,101 Liberty St,btwn Church & Greenwich St,40.710075,-74.011976,"[{'label': 'display', 'lat': 40.710075, 'lng':...",...,United States,"[101 Liberty St (btwn Church & Greenwich St), ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,58d933702f91cb026f478e38,East One Coffee Roasters,"[{'id': '4bf58dd8d48988d1e0931735', 'name': 'C...",v-1587267800,False,384 Court St,at Carroll St,40.681128,-73.996526,"[{'label': 'display', 'lat': 40.68112803526681...",...,United States,"[384 Court St (at Carroll St), Brooklyn, NY 11...",1153265,https://www.seamless.com/menu/east-one-coffee-...,seamless,https://fastly.4sqi.net/img/general/cap/,"[40, 50]",/delivery_provider_seamless_20180129.png,Carroll Gardens,NaN
21,5e5454fd0906ab000b3f9b53,Levain Bakery,"[{'id': '4bf58dd8d48988d16a941735', 'name': 'B...",v-1587267800,False,340 Lafayette St,NaN,40.726140,-73.994700,"[{'label': 'display', 'lat': 40.72614, 'lng': ...",...,United States,"[340 Lafayette St, New York, NY 10012, United ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,42f15a80f964a520bb261fe3,Olive Garden,"[{'id': '4bf58dd8d48988d110941735', 'name': 'I...",v-1587267800,False,2 Times Sq,W 47th St,40.759414,-73.984702,"[{'label': 'display', 'lat': 40.75941434851957...",...,United States,"[2 Times Sq (W 47th St), New York, NY 10036, U...",833910,https://www.seamless.com/menu/olive-garden-2-t...,seamless,https://fastly.4sqi.net/img/general/cap/,"[40, 50]",/delivery_provider_seamless_20180129.png,NaN,NaN
23,4c684d7473851b8dd845ba39,The Loeb Boathouse,"[{'id': '4bf58dd8d48988d14e941735', 'name': 'A...",v-1587267800,False,E 72nd St,Park Dr N,40.775285,-73.968780,"[{'label': 'display', 'lat': 40.77528495950326...",...,United States,"[E 72nd St (Park Dr N), New York, NY 10028, Un...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,5bf07de3bcbf7a002cd8d9f3,Japan Village,"[{'id': '4bf58dd8d48988d111941735', 'name': 'J...",v-1587267800,False,934 3rd Ave,btwn 35th & 36th St,40.655904,-74.006110,"[{'label': 'display', 'lat': 40.65590374239456...",...,United States,"[934 3rd Ave (btwn 35th & 36th St), Brooklyn, ...",2047700,https://www.seamless.com/menu/japan-village-93...,seamless,https://fastly.4sqi.net/img/general/cap/,"[40, 50]",/delivery_provider_seamless_20180129.png,Greenwood Heights,NaN
25,5716655d498e23619f894ef0,TurnStyle Underground Market,"[{'id': '4bf58dd8d48988d120951735', 'name': 'F...",v-1587267800,False,1000 S 8th Ave,btwn 57th & 58th St,40.767081,-73.982569,"[{'label': 'display', 'lat': 40.767081, 'lng':...",...,United States,"[1000 S 8th Ave (btwn 57th & 58th St), New Yor...",1104490,https://www.seamless.com/menu/taheni-grill-at-...,seamless,https://fastly.4sqi.net/img/general/cap/,"[40, 50]",/delivery_provider_seamless_20180129.png,NaN,NaN
26,4ada106af964a520ed1d21e3,Starbucks,"[{'id': '4bf58dd8d48988d1e0931735', 'name': 'C...",v-1587267800,False,72 Grove St,at 7th Ave S,40.733180,-74.002930,"[{'label': 'display', 'lat': 40.73318, 'lng': ...",...,United States,"[72 Grove St (at 7th Ave S), New York, NY 1001...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,54b80565498e6d4f36168cd8,Xi'an Famous Foods,"[{'id': '4bf58dd8d48988d145941735', 'name': 'C...",v-1587267800,False,14 E 34th St,NaN,40.748165,-73.984003,"[{'label': 'display', 'lat': 40.74816543859803...",...,United States,"[14 E 34th St, New York, NY 10016, United States]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,59035bc43d47912d4b97f3fc,Xi'an Famous Foods,"[{'id': '4bf58dd8d48988d145941735', 'name': 'C...",v-1587267800,False,38 E 23rd St,NaN,40.740632,-73.987346,"[{'label': 'display', 'lat': 40.74063210444959...",...,United States,"[38 E 23rd St, New York, NY 10010, United States]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,591f17e0c9f9074efb17166c,Za-Ya Ramen,"[{'id': '55a59bace4b013909087cb24', 'name': 'R...",v-1587267800,False,545 Court St,btwn Hamilton Ave & Garnet St,40.674224,-73.999877,"[{'label': 'display', 'lat': 40.67422356225874...",...,United States,"[545 Court St (btwn Hamilton Ave & Garnet St),...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
dataframe_NewYork.insert(24,"area","New York")
dataframe_NewYork.head()

,id,name,categories,referralId,hasPerk,location.address,location.crossStreet,location.lat,location.lng,location.labeledLatLngs,...,location.formattedAddress,delivery.id,delivery.url,delivery.provider.name,delivery.provider.icon.prefix,delivery.provider.icon.sizes,delivery.provider.icon.name,location.neighborhood,venuePage.id,area
0,4c5ef77bfff99c74eda954d3,Eataly Flatiron,"[{'id': '4bf58dd8d48988d1f5941735', 'name': 'G...",v-1587267800,False,200 5th Ave,at W 23rd St,40.741987,-73.989913,"[{'label': 'display', 'lat': 40.74198696405861...",...,"[200 5th Ave (at W 23rd St), New York, NY 1001...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New York
1,5b76dcc19fca56002de565df,Dunkin',"[{'id': '4bf58dd8d48988d148941735', 'name': 'D...",v-1587267800,False,1410 N Broad St,NaN,40.697855,-74.217544,"[{'label': 'display', 'lat': 40.69785456739121...",...,"[1410 N Broad St, Hillside, NJ 07205, United S...",1394893,https://www.grubhub.com/restaurant/dunkin-1410...,grubhub,https://fastly.4sqi.net/img/general/cap/,"[40, 50]",/delivery_provider_grubhub_20180129.png,NaN,NaN,New York
2,562e8930498e260cde609d13,Armando's Kitchen,"[{'id': '4bf58dd8d48988d110941735', 'name': 'I...",v-1587267800,False,1345 Rockaway Pkwy,NaN,40.646856,-73.904189,"[{'label': 'display', 'lat': 40.64685639184821...",...,"[1345 Rockaway Pkwy, Brooklyn, NY 11236, Unite...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New York
3,5cf465f1829b0c002c5552f7,Coolsville,"[{'id': '4bf58dd8d48988d157941735', 'name': 'N...",v-1587267800,False,NaN,NaN,40.860077,-73.930597,"[{'label': 'display', 'lat': 40.860077, 'lng':...",...,"[New York, NY 10040, United States]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New York
4,40e74880f964a520150a1fe3,Shake Shack,"[{'id': '4bf58dd8d48988d16c941735', 'name': 'B...",v-1587267800,False,Southeast corner of Madison Square Park,Madison Ave & E 23rd St,40.741484,-73.988218,"[{'label': 'display', 'lat': 40.74148371088094...",...,[Southeast corner of Madison Square Park (Madi...,698246,https://www.seamless.com/menu/shake-shack-23rd...,seamless,https://fastly.4sqi.net/img/general/cap/,"[40, 50]",/delivery_provider_seamless_20180129.png,Flatiron,NaN,New York

In [15]:
near ='Seattle,WA'
url = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&near={}&categoryId={}&v={}&limit={}'.format(CLIENT_ID, CLIENT_SECRET, near, categoryId, VERSION, LIMIT)
url
results = requests.get(url).json()

venues = results['response']['venues']

dataframe_Seattle = json_normalize(venues)
dataframe_Seattle.insert(24, "area", "Seattle")
dataframe_Seattle.head()

near ='San Francisco,CA'
url = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&near={}&categoryId={}&v={}&limit={}'.format(CLIENT_ID, CLIENT_SECRET, near, categoryId, VERSION, LIMIT)
url
results = requests.get(url).json()

venues = results['response']['venues']

dataframe_SF = json_normalize(venues)
dataframe_SF.insert(24, "area", "San Francisco")
dataframe_SF.head()

near ='Shanghai,China'
url = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&near={}&categoryId={}&v={}&limit={}'.format(CLIENT_ID, CLIENT_SECRET, near, categoryId, VERSION, LIMIT)
url
results = requests.get(url).json()

venues = results['response']['venues']

dataframe_Shanghai= json_normalize(venues)
dataframe_Shanghai.insert(17,"area", "Shanghai")

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/ipykernel_launcher.py:8: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/ipykernel_launcher.py:19: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/ipykernel_launcher.py:30: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead

create a consolidate dataframe for further analyses after filtering to keep only information that's relevant

In [16]:
print(dataframe_NewYork.shape)
print(dataframe_Seattle.shape)
print(dataframe_Shanghai.shape)
print(dataframe_SF.shape)

df_analysis=dataframe_NewYork.append([dataframe_Shanghai, dataframe_SF, dataframe_Seattle])

(30, 25)
(30, 25)
(29, 18)
(30, 25)

In [17]:
df_analysis.shape

(119, 25)

In [18]:
df_analysis.head()

,id,name,categories,referralId,hasPerk,location.address,location.crossStreet,location.lat,location.lng,location.labeledLatLngs,...,location.formattedAddress,delivery.id,delivery.url,delivery.provider.name,delivery.provider.icon.prefix,delivery.provider.icon.sizes,delivery.provider.icon.name,location.neighborhood,venuePage.id,area
0,4c5ef77bfff99c74eda954d3,Eataly Flatiron,"[{'id': '4bf58dd8d48988d1f5941735', 'name': 'G...",v-1587267800,False,200 5th Ave,at W 23rd St,40.741987,-73.989913,"[{'label': 'display', 'lat': 40.74198696405861...",...,"[200 5th Ave (at W 23rd St), New York, NY 1001...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New York
1,5b76dcc19fca56002de565df,Dunkin',"[{'id': '4bf58dd8d48988d148941735', 'name': 'D...",v-1587267800,False,1410 N Broad St,NaN,40.697855,-74.217544,"[{'label': 'display', 'lat': 40.69785456739121...",...,"[1410 N Broad St, Hillside, NJ 07205, United S...",1394893,https://www.grubhub.com/restaurant/dunkin-1410...,grubhub,https://fastly.4sqi.net/img/general/cap/,"[40, 50]",/delivery_provider_grubhub_20180129.png,NaN,NaN,New York
2,562e8930498e260cde609d13,Armando's Kitchen,"[{'id': '4bf58dd8d48988d110941735', 'name': 'I...",v-1587267800,False,1345 Rockaway Pkwy,NaN,40.646856,-73.904189,"[{'label': 'display', 'lat': 40.64685639184821...",...,"[1345 Rockaway Pkwy, Brooklyn, NY 11236, Unite...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New York
3,5cf465f1829b0c002c5552f7,Coolsville,"[{'id': '4bf58dd8d48988d157941735', 'name': 'N...",v-1587267800,False,NaN,NaN,40.860077,-73.930597,"[{'label': 'display', 'lat': 40.860077, 'lng':...",...,"[New York, NY 10040, United States]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New York
4,40e74880f964a520150a1fe3,Shake Shack,"[{'id': '4bf58dd8d48988d16c941735', 'name': 'B...",v-1587267800,False,Southeast corner of Madison Square Park,Madison Ave & E 23rd St,40.741484,-73.988218,"[{'label': 'display', 'lat': 40.74148371088094...",...,[Southeast corner of Madison Square Park (Madi...,698246,https://www.seamless.com/menu/shake-shack-23rd...,seamless,https://fastly.4sqi.net/img/general/cap/,"[40, 50]",/delivery_provider_seamless_20180129.png,Flatiron,NaN,New York

In [19]:
# keep only columns that include venue name, and anything that is associated with location
filtered_columns = ['name', 'categories'] + [col for col in df_analysis.columns if col.startswith('location.')] + ['id']+['area']
df_filtered = df_analysis.loc[:, filtered_columns]

# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

# filter the category for each row
df_filtered['categories'] = df_filtered.apply(get_category_type, axis=1)

# clean column names by keeping only last term
df_filtered.columns = [column.split('.')[-1] for column in df_filtered.columns]

df_filtered

,name,categories,address,crossStreet,lat,lng,labeledLatLngs,postalCode,cc,city,state,country,formattedAddress,neighborhood,id,area
0,Eataly Flatiron,Gourmet Shop,200 5th Ave,at W 23rd St,40.741987,-73.989913,"[{'label': 'display', 'lat': 40.74198696405861...",10010,US,New York,NY,United States,"[200 5th Ave (at W 23rd St), New York, NY 1001...",NaN,4c5ef77bfff99c74eda954d3,New York
1,Dunkin',Donut Shop,1410 N Broad St,NaN,40.697855,-74.217544,"[{'label': 'display', 'lat': 40.69785456739121...",07205,US,Hillside,NJ,United States,"[1410 N Broad St, Hillside, NJ 07205, United S...",NaN,5b76dcc19fca56002de565df,New York
2,Armando's Kitchen,Italian Restaurant,1345 Rockaway Pkwy,NaN,40.646856,-73.904189,"[{'label': 'display', 'lat': 40.64685639184821...",11236,US,Brooklyn,NY,United States,"[1345 Rockaway Pkwy, Brooklyn, NY 11236, Unite...",NaN,562e8930498e260cde609d13,New York
3,Coolsville,New American Restaurant,NaN,NaN,40.860077,-73.930597,"[{'label': 'display', 'lat': 40.860077, 'lng':...",10040,US,New York,NY,United States,"[New York, NY 10040, United States]",NaN,5cf465f1829b0c002c5552f7,New York
4,Shake Shack,Burger Joint,Southeast corner of Madison Square Park,Madison Ave & E 23rd St,40.741484,-73.988218,"[{'label': 'display', 'lat': 40.74148371088094...",10010,US,New York,NY,United States,[Southeast corner of Madison Square Park (Madi...,Flatiron,40e74880f964a520150a1fe3,New York
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25,Costco Food Court,Food Court,NaN,NaN,47.834468,-122.272776,"[{'label': 'display', 'lat': 47.83446773075105...",NaN,NaN,NaN,Washington,NaN,[Washington],NaN,57be5e55cd10835976c40813,Seattle
26,Costco Food Court,American Restaurant,NaN,NaN,47.681152,-122.181481,"[{'label': 'display', 'lat': 47.68115174212198...",NaN,US,Kirkland,WA,United States,"[Kirkland, WA, United States]",NaN,557b3732498e9ec2000cfbc7,Seattle
27,Sea Wolf Bakery,Bakery,3621 Stone Way N,N 36th St,47.651034,-122.343053,"[{'label': 'display', 'lat': 47.65103415759725...",98103,US,Seattle,WA,United States,"[3621 Stone Way N (N 36th St), Seattle, WA 981...",NaN,578d2845cd1046e59b14c111,Seattle
28,Analog Coffee,Coffee Shop,235 Summit Ave E,at Thomas St,47.620768,-122.325448,"[{'label': 'display', 'lat': 47.620768, 'lng':...",98102,US,Seattle,WA,United States,"[235 Summit Ave E (at Thomas St), Seattle, WA ...",NaN,4d4463c2bbb1a14344fc4572,Seattle
29,Starbucks,Coffee Shop,2902 164th St SW,NaN,47.847698,-122.272854,"[{'label': 'display', 'lat': 47.84769798575758...",98087,US,Lynnwood,WA,United States,"[2902 164th St SW, Lynnwood, WA 98087, United ...",NaN,4c7c787a9efda1433aff85e2,Seattle

identify variety of cushine in each city

In [20]:
summary=df_filtered.groupby(['categories','area']).size().reset_index(name='counts')

In [21]:
summary.sort_values(by=['area','counts'], ascending=False)

                 categories      area  counts
23              Coffee Shop  Shanghai       8
7                    Bakery  Shanghai       3
43        Hotpot Restaurant  Shanghai       2
46       Italian Restaurant  Shanghai       2
8                       Bar  Shanghai       1
..                      ...       ...     ...
47      Japanese Restaurant  New York       1
51  New American Restaurant  New York       1
57            Poutine Place  New York       1
58         Ramen Restaurant  New York       1
62              Supermarket  New York       1

[65 rows x 3 columns]

In [25]:
variety=summary.groupby('area').size().reset_index(name='categories')
variety

            area  categories
0       New York          16
1  San Francisco          16
2        Seattle          15
3       Shanghai          18

In [32]:
summary[summary.area=='New York'].sort_values(by='counts', ascending=False).head()

            categories      area  counts
20         Coffee Shop  New York       4
34          Food Court  New York       4
4               Bakery  New York       3
39       Grocery Store  New York       3
45  Italian Restaurant  New York       3

In [31]:
summary[summary.area=='Shanghai'].sort_values(by='counts', ascending=False).head()

              categories      area  counts
23           Coffee Shop  Shanghai       8
7                 Bakery  Shanghai       3
46    Italian Restaurant  Shanghai       2
43     Hotpot Restaurant  Shanghai       2
17  Cantonese Restaurant  Shanghai       1

In [33]:
summary[summary.area=='Seattle'].sort_values(by='counts', ascending=False).head()

              categories     area  counts
22           Coffee Shop  Seattle       5
12          Burger Joint  Seattle       4
32  Fast Food Restaurant  Seattle       4
36            Food Court  Seattle       3
1    American Restaurant  Seattle       2

In [34]:
summary[summary.area=='San Francisco'].sort_values(by='counts', ascending=False).head()

              categories           area  counts
21           Coffee Shop  San Francisco       6
40         Grocery Store  San Francisco       4
5                 Bakery  San Francisco       3
31  Fast Food Restaurant  San Francisco       3
35            Food Court  San Francisco       3

In [37]:
summary.groupby('area').sum()

               counts
area
New York           30
San Francisco      30
Seattle            30
Shanghai           29